### ISSUE TITLE
Topic Page: Create Topic Wizard (show all available options ON)

### ISSUE THREAD

**Issue by christiemolloy** [bf2fc6cc711aee1a0c2a/uxd-mk-data-plane-ui#5]
Create topic wizard with all available options turned ON.
@jgiardino , looks like the design is cut off underneath messages.. are there designs that incorporate the content underneath messages?

https://marvelapp.com/prototype/26598gag/screen/73803095

**Comment by jgiardino** [comment]
@lboehling - Do you have examples of the other sections that display for the "all available options" topic creation?

**Comment by lboehling** [comment]
@jgiardino @christiemolloy yep, i'll update the marvel prototype with the full display. I need to import it from another sketch file.

**Comment by lboehling** [comment]
Full create topics page has been updated in the marvel doc: https://marvelapp.com/prototype/26598gag/screen/73803095 

@christiemolloy

**Comment by christiemolloy** [comment]
Completed
